### ISSUE TITLE
question regarding Chord.intervals

### ISSUE THREAD

**Issue by mattmarcello** [cemolcay/MusicTheory#33]
Quick question regarding this block of code in `Chord.swift`:

```
  /// Intervals of parts between root.
  public var intervals: [Interval] {
    var parts: [ChordPart?] = [sixth == nil ? third : nil, suspended, fifth, sixth, seventh]
    parts += extensions?.sorted(by: { $0.type.rawValue < $1.type.rawValue }).map({ $0 as ChordPart? }) ?? []
    return [.P1] + parts.compactMap({ $0?.interval })
  }
```

I am a bit confused as to why the presence of a `sixth` chord type results in the omission of the `third` interval from the resultant interval list.  Granted, I am no expert in music theory.  :)

**Comment by maksutovic** [comment]
Hi @mattmarcello I just submitted a pullrequest which @cemolcay approved that corrected this issue. This should be updated in the next release!
