### ISSUE TITLE
ChordTypeExtensions: Automatic Addition of 9th with 11th extension and 9th+11th with 13th Extension

### ISSUE THREAD

**Issue by maksutovic** [cemolcay/MusicTheory#37]
<img width="702" alt="57576405-e3bd7600-7424-11e9-8792-622b99a84f76" src="https://user-images.githubusercontent.com/1383383/57576572-7525eb80-7417-11e9-8d69-6805fe724ea3.png">

When making 7th chords with extensions, if you request just a 11th, ChordTypeExtensions automatically adds a 9th. With 13ths, a 9th and 11th are added automatically. 

I know there are schools of thought that this makes the most sense, however I feel it's a little presumptive that a user always wants a 9th or 11th. 

I'd like to do a pull request and augment this, but I wanted to get your reasoning first @cemolcay

**Comment by AtharvaVaidya** [comment]
@cemolcay any updates on this?
