### ISSUE TITLE
Using A4 instead of d5 on Lydian scale

### ISSUE THREAD

**Issue by Brassack** [cemolcay/MusicTheory#39]
Hi @cemolcay !
I noticed lydian scale have a diminished fifth on step IV

Based on wikipedia
https://en.wikipedia.org/wiki/Lydian_mode
>  The Lydian scale can be described as a major scale with the fourth scale degree raised a semitone, making it an augmented fourth above the tonic, e.g., an F-major scale with a B♮ rather than B♭.

I assume code:

`public static let lydian = ScaleType(intervals: [.P1, .M2, .M3, .d5, .P5, .M6, .M7], description: "Lydian")
`

 should use augmented fourth instead diminished fifth

`public static let lydian = ScaleType(intervals: [.P1, .M2, .M3, .A4, .P5, .M6, .M7], description: "Lydian")
`

I working on my pet project which works with scale calculations.
App take key and perform scale's Interval calculation(added code sample below)

I had noticed i have incorrect results on lydian scale
e.g if you calculate lydian a-flat
app should have
A♭ B♭ C D E♭ F G
https://www.basicmusictheory.com/a-flat-lydian-mode
Using library i have
A♭ B♭ C E𝄫 E♭ F G

Sample code

```
let key = Key(type: .a, accidental: .flat)
print("Root ", key)
for (index, interval) in ScaleType.lydian.intervals.enumerated() {
    let key = (Pitch(key: key, octave: 0) + interval).key
    print(index, " = ", key)
}
```

Does it makes any sence?
Thank you.

**Comment by cemolcay** [comment]
Fixed on #6634304 
https://github.com/cemolcay/MusicTheory/commit/6634304c2c4c4ce475006a19a861ef65ef84477a
