### ISSUE TITLE
Get absolute value of Key

### ISSUE THREAD

**Issue by Yetispapa** [cemolcay/MusicTheory#42]
Is it somehow possible to get the absolute value of a key like so?

```
let c = Key(type: .c)
let absoluteValueOfC = c.absoluteValue // 60
```

The background is that I want to play the absoluteValue with a midi sequencer. So it would be great if I could declare a chord like this:

`let cm13 = Chord(type: m13, key: Key(type: .c))`

and iterate through their keys to pass it to the sequencer

Is that somehow possible?

**Comment by cemolcay** [comment]
Hi!

If you want to get the MIDI value, then you can use `Pitch` struct and use it `rawValue` which is the MIDI key value.
So, after creating a chord, you can create pitches for that chord:

```
let cm13 = Chord(type: m13, key: Key(type: .c))
let chordNotes = cm13.pitches(octave: 3)
```

And then you can map the pitches to the MIDI values:

```
chordNotes.map{ $0.rawValue }
```

Hope this helps!

**Comment by Yetispapa** [comment]
Great! Thanks for the quick response and great framework of course
