### ISSUE TITLE
Chords equal issue

### ISSUE THREAD

**Issue by KittenYang** [cemolcay/MusicTheory#47]
Currently, two chords whether equal just determined by `Key` and `ChordType`, not contains `inversion`. So C/E and C is equal:
```swift
let c_e: Chord = Chord(type: ChordType(third: .major), key: Key(type: .c), inversion: 1)
let c: Chord = Chord(type: ChordType(third: .major), key: Key(type: .c), inversion: 0)
c_e == c // true
```

But the truth is C/E ≠ C.

Please add `inversion` condition to the Chord's  `public func == (left: Chord?, right: Chord?) -> Bool` method.
```swift
public func == (left: Chord?, right: Chord?) -> Bool {
  switch (left, right) {
  case let (.some(left), .some(right)):
    return left.key == right.key && left.type == right.type && left.inversion == right.inversion
  case (.none, .none):
    return true
  default:
    return false
  }
}
```

**Comment by cemolcay** [comment]
Updated, thanks!

https://github.com/cemolcay/MusicTheory/commit/ce34fa6abced31888eb53ab2b15ab170e108b4cc
