### ISSUE TITLE
Lydian Augmented #6 is incomplete, just the root right now

### ISSUE THREAD

**Issue by aure** [cemolcay/MusicTheory#49]
https://github.com/cemolcay/MusicTheory/blob/db3b3cc1c8803813e5e4d29afb87da881ca74c7c/Sources/MusicTheory/ScaleType.swift#L351

**Comment by cemolcay** [comment]
#50

**Comment by aure** [comment]
I don't necessarily know the best way to fix this, but the way these scales are defined seems to highlight a problem with this library in that the spelling of the scales is quite off.  To the best of my understanding, every scale degree should have its own letter. Or, to put it another way, there can only be one 2nd, one 3rd, one 4, etc. in each scale.
